// <auto-generated />
using System;
using Livraria.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Livraria.Persistance.Migrations
{
    [DbContext(typeof(DataBaseService))]
    partial class DataBaseServiceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Livraria.Domain.Livros.Livro", b =>
                {
                    b.Property<string>("ISBN")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Autor")
                        .HasMaxLength(1500);

                    b.Property<byte[]>("Capa");

                    b.Property<DateTime>("DataPublicacao");

                    b.Property<string>("Nome")
                        .HasMaxLength(1500);

                    b.Property<decimal>("Preco");

                    b.HasKey("ISBN");

                    b.ToTable("Livro");
                });
#pragma warning restore 612, 618
        }
    }
}
